### ISSUE TITLE
POSIX timers for zephyr fix in rcutils is not being reflected in the humble release

### ISSUE THREAD

**Issue by uLipe** [micro-ROS/micro_ros_zephyr_module#103]
- RTOS: Zephyr
- Installation type: module
- Version or commit hash: humble

#### Steps to reproduce the issue
After cloning a fresh copy of micro ROS module for zephyr I was not able to build because problems with posix time implementation for Zephyr. It seems the current humble release is not reflecting the fix that was submitted to the rcutils: https://github.com/ros2/rcutils/pull/390

#### Expected behavior
It shoud build the binary to be flashed to the board using west flash

#### Actual behavior
It fails during the build, pointing error in the posix/time.h path for zephyr.

**Comment by uLipe** [comment]
@pablogs9 @Acuadros95 could you please clarify?

Looking at the humble branch on the rcutils, it seems the additions for handling Zephyr posix time are not there:

https://github.com/ros2/rcutils/blob/6724d8a0f842e13cac07f2e90a06f79ae6fcfc48/src/time_unix.c#L38

**Comment by uLipe** [comment]
@microbuilder, you might be interested on this.

**Comment by pablogs9** [comment]
@uLipe https://github.com/ros2/rcutils/pull/390 targets `rolling` branch has not been backported to `humble`, in any case I backported manually to the micro-ROS branch.

Here you can see the `origin/ros2` branch and the micro-ROS branch above:

![image](https://user-images.githubusercontent.com/7647884/198199697-15bd861b-3e5c-4610-9854-01ccbcdf664d.png)

For me is easier to manually backport to micro-ROS but ideally, changes shall be backported in ROS 2 package. Could you take a look at the git tree and tell me which PR should I backport?

**Comment by uLipe** [comment]
@pablogs9 thanks for the clarification, to get the microROS working fine across the Zephyr versions we discussed previously the PR I flagged above is required, would you be able to backport it to humble?

**Comment by pablogs9** [comment]
Yes but please, let me know which commit do you need to backport to humble branch

**Comment by uLipe** [comment]
@pablogs9, sure the missing commit I see is:


4767778eba04f11eaa4a924648ff4bca5433396c

**Comment by pablogs9** [comment]
![image](https://user-images.githubusercontent.com/7647884/198508961-1eef01d3-80bf-4e83-8379-f98a8051cc63.png)

Let me know if this works for you

**Comment by uLipe** [comment]
@pablogs9 , this works fine to me.

Thank you for your support.

**Comment by pablogs9** [comment]
Cool. Closing, reopen if not solved.
