### ISSUE TITLE
std_srvs location

### ISSUE THREAD

**Issue by gseqBE** [micro-ROS/micro_ros_zephyr_module#106]
Hardware description:
nucleo_h743zi
RTOS:
Installation type:
Version or commit hash:
Humble

We are moving towards zephyr microros module from the  non-module style.

There are a couple of services we are using, specifically trigger style service.
There used to be a std_srvs/srv under /mcu_ws/install/include/std_srvs/ in the non-module style and using it as below seemed to work.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/2365134/204932288-b10ba423-6520-480d-838d-eef32589fa3e.png">

I'm unable to find the std services in the module solution. Has it moved?
This is what my modules/libmicroros/include folder looks like:
<img width="202" alt="image" src="https://user-images.githubusercontent.com/2365134/204932810-65206091-cf8d-400b-8e07-57fa988dc6dd.png">

Thank you!

**Comment by pablogs9** [comment]
Here you have the whole list of packages that micro-ROS uses for its building, including msg and srv packages: https://github.com/micro-ROS/micro_ros_zephyr_module/blob/humble/modules/libmicroros/libmicroros.mk#L75-L94

If your required package is not available, please add it manually.

Also, it would be nice to have a way to include "user packages" as in [other modules](https://github.com/micro-ROS/micro_ros_espidf_component/tree/humble/extra_packages).

**Comment by gseqBE** [comment]
If I comment out https://github.com/micro-ROS/micro_ros_zephyr_module/blob/humble/modules/libmicroros/libmicroros.mk#L98

or remove the COLCON_IGNORE from: src/common_interfaces/std_srvs folder, so it is not under separate package, but under common interfaces. Is it possible to allow it by default?

**Comment by pablogs9** [comment]
Please open a PR with your suggestions.
