### ISSUE TITLE
Error : undefined reference to '__device_dts_ord_18'

### ISSUE THREAD

**Issue by sachinjairam** [micro-ROS/micro_ros_zephyr_module#44]
Hai, I am trying to read ADC values for Nucleo-H743ZI board with Zephyr microROS. 
But, while building the firmware an unknown error occurs.

![oie_xhJx2XTIHUXN](https://user-images.githubusercontent.com/44083276/150920824-22d6d671-3538-48a4-8738-1e80797d9a29.png)

I couldn't find any solution. So please advise me how to solve this problem.

Thank you,
Sachin

**Comment by pablogs9** [comment]
Not related to micro-ROS
