### ISSUE TITLE
nRF52 support over Zephyr

### ISSUE THREAD

**Issue by Manucar** [micro-ROS/micro_ros_zephyr_module#60]
Hi,
I was wondering if there are already on-going porting for the Nordic family (specifically nRF52840), and if not, are there some references I can look into to add hardware support for it?

Thank you for your time!

**Comment by pablogs9** [comment]
You should be able to use this component as it is with your boards if it is supported by Zephyr.

Did you have any problem?

**Comment by pablogs9** [comment]
I have tested the whole process with your board, here you have my session: https://asciinema.org/a/Vpcvaj7wgAqTRv8Y3Gbs8hoHp

The final error is that the board has not enough memory (this SoC has 24 kB? this will be challenging)... In any case, you can check [this tutorial](https://micro.ros.org/docs/tutorials/advanced/microxrcedds_rmw_configuration/) for tunning the micro-ROS memory usage.

**Comment by Manucar** [comment]
Ok definitely this SoC is not powerful enough, I will upgrade to the next version "ubx_bmd380eval_nrf52840". Following your video and compiling for this new board, it gives me no error! So when the board will arrive I think the flashing will be okay, I will let you know.

Thank you very much for your precious help!

**Comment by pablogs9** [comment]
Nice, I'm closing. Feel free to open another issue if you have further problems.

**Comment by Manucar** [comment]
Hi @pablogs9, the board is arrived and I flashed the built image, but it remains stuck in this function (as far as I can see with gdb):

```python
(gdb) c
Continuing.
^C
Program received signal SIGTRAP, Trace/breakpoint trap.
0x000018de in main () at ../src/main.c:54
54		RCCHECK(rclc_support_init_with_options(&support, 0, NULL, &init_options, &allocator));

```

and on the agent side:
```C
(base) manucar@D311:~$ docker run -it --rm -v /dev:/dev --privileged --net=host microros/micro-ros-agent:humble serial --dev /dev/ttyACM1 -v6
[1654605220.329402] info     | TermiosAgentLinux.cpp | init                     | running...             | fd: 3
[1654605220.329568] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 6

```
I compiled the example on this repo with the same steps of your video (for the actual board: ubx_bmd380eval_nrf52840).
Do you think anything I can try?

Thanks!

**Comment by pablogs9** [comment]
Make sure that your board is reaching the PC via `/dev/ttyACM1`. Make sure that your serial ports are working ok before using it for micro-ROS client transport.

**Comment by Manucar** [comment]
Hi @pablogs9, okay after some debugging I find out that for some reason in this function for opening the transport layer:

```C

bool zephyr_transport_open(struct uxrCustomTransport * transport){
    zephyr_transport_params_t * params = (zephyr_transport_params_t*) transport->args;

    char uart_descriptor[8];
    sprintf(uart_descriptor,"UART_%d", params->fd);
    params->uart_dev = device_get_binding(uart_descriptor);
    if (!params->uart_dev) {
        printk("Serial device not found\n");
        return false;
    }
...
```
the 'params->fd' field was set to 1, so it was opening the UART_1, changing it to '0' -> `UART_0` make it works.

I was also wondering if it is feasible/reliable implementing mirco-ROS over the BLE 5.0 transport protocol with this nRF chip for streaming data from a sensor @200 Hz? 

Thank you as always!
